import { useEffect } from 'react';

/**
 * WHY THIS EXISTS:
 *
 * Browsers (especially Safari) can emit *synthetic pointer events*
 * during keyboard navigation, focus transitions, or layout changes—
 * particularly when overlays or absolute-positioned UI are involved.
 *
 * Without guarding against untrusted events (event.isTrusted === false),
 * normal keyboard actions like Tab can incorrectly trigger "click outside"
 * dismissal logic, causing focused UI to disappear mid-navigation.
 *
 * This hook explicitly ignores untrusted pointer events so that:
 * - Mouse/touch interactions dismiss UI as expected
 * - Keyboard and screen-reader navigation remain stable
 * - Accessibility and overlay behavior do not fight each other
 *
 * Do not remove the `isTrusted` guard unless you enjoy debugging ghosts.
 */
export function useOutsideDismiss({
  enabled = true,
  refs = [],
  onDismiss,
}) {
  useEffect(() => {
    if (!enabled) return;

    const handlePointerDown = (e) => {
      // 🔒 CRITICAL: Ignore synthetic pointer events generated by the browser
      if (!e.isTrusted) return;

      const isInside = refs.some((ref) => {
        const el = ref?.current;
        return el && el.contains(e.target);
      });

      if (!isInside) {
        onDismiss?.();
      }
    };

    document.addEventListener('pointerdown', handlePointerDown, true);

    return () => {
      document.removeEventListener('pointerdown', handlePointerDown, true);
    };
  }, [enabled, refs, onDismiss]);
}