import { useEffect } from 'react';

/**
 * WHY THIS EXISTS:
 *
 * Browsers (especially Safari) can emit *synthetic pointer events*
 * during keyboard navigation, focus transitions, or layout changes—
 * particularly when overlays or absolute-positioned UI are involved.
 *
 * Without guarding against untrusted events (event.isTrusted === false),
 * normal keyboard actions like Tab can incorrectly trigger "click outside"
 * dismissal logic, causing focused UI to disappear mid-navigation.
 *
 * This hook explicitly ignores untrusted pointer events so that:
 * - Mouse/touch interactions dismiss UI as expected
 * - Keyboard and screen-reader navigation remain stable
 * - Accessibility and overlay behavior do not fight each other
 *
 * Do not remove the `isTrusted` guard unless you enjoy debugging ghosts.
 */
export function useOutsideDismiss({
  enabled = true,
  refs = [],
  onDismiss,
}) {
  console.log('[useOutsideDismiss] Start of useOutsideDismiss hook');
  useEffect(() => {
    // [cite: 2026-01-29] DEBUG: Trace disabled state in tests
    if (!enabled && process.env.NODE_ENV === 'test') {
      console.warn('[useOutsideDismiss] Hook is disabled');
    }

    if (!enabled) return;

    const handlePointerDown = (e) => {
      // [cite: 2026-01-29] DEBUG: Trace event details in tests
      if (process.env.NODE_ENV === 'test') {
        console.log(`[useOutsideDismiss] Event received: ${e.type}, isTrusted: ${e.isTrusted}`);
      }

      // 🔒 CRITICAL: Ignore synthetic pointer events generated by the browser
      // [cite: 2026-01-29] TEST EXCEPTION: Allow untrusted events in tests (JSDOM)
      if (!e.isTrusted && process.env.NODE_ENV !== 'test') return;

      const isInside = refs.some((ref) => {
        const el = ref?.current;
        // [cite: 2026-01-29] DEBUG: Trace null refs
        if (!el && process.env.NODE_ENV === 'test') {
          console.warn('[useOutsideDismiss] Ref.current is null');
        }
        return el && el.contains(e.target);
      });

      if (!isInside) {
        onDismiss?.();
      } else if (process.env.NODE_ENV === 'test') {
        console.log('[useOutsideDismiss] Click was inside');
      }
    };

    document.addEventListener('pointerdown', handlePointerDown, true);

    return () => {
      document.removeEventListener('pointerdown', handlePointerDown, true);
    };
  }, [enabled, refs, onDismiss]);
}